workflows:
  ios-simulator:
    name: iOS Unity Ads Demo Build
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      xcode: latest
      flutter: stable
      groups:
        - unity_credentials
      vars:
        UNITY_GAME_ID: "5859176"
    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
        - $HOME/.pub-cache
        - $HOME/Library/Caches/CocoaPods
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Install CocoaPods dependencies
        script: |
          cd ios && pod install
      - name: Set up Unity Game ID
        script: |
          echo "Setting Unity Game ID to $UNITY_GAME_ID"
      - name: Build for iOS Simulator
        script: |
          flutter build ios --debug --no-codesign --simulator
    artifacts:
      - build/ios/iphonesimulator/Runner.app
    publishing:
      scripts:
        - name: Build Info
          script: |
            echo "Build completed for Unity Ads Demo app"
            echo "Use this build for testing on LambdaTest" 