workflows:
  ios-simulator-build:
    name: iOS Simulator Build
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      xcode: latest
      flutter: stable
      ios_signing:
        distribution_type: development
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Install pods
        script: |
          cd ios && pod install
      - name: Set up for simulator build
        script: |
          flutter clean
          flutter pub get
      - name: Build for iOS Simulator
        script: |
          flutter build ios --debug --no-codesign --simulator
          # Create a zip of the app for easy upload to LambdaTest
          cd build/ios/iphonesimulator
          zip -r ../simulator_app.zip *.app
    artifacts:
      - build/ios/simulator_app.zip
      - build/ios/iphonesimulator/*.app
    publishing:
      email:
        recipients:
          - user@example.com # Replace with your email
        notify:
          success: true
          failure: true 