workflows:
  ios-simulator:
    name: iOS Simulator Build
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      xcode: latest
      flutter: stable
      ios_signing:
        distribution_type: development
        bundle_identifier: com.example.iosTapToPaid
    cache:
      cache_paths:
        - ~/.pub-cache
        - ~/.cocoapods
    scripts:
      - name: Set up code signing settings
        script: |
          echo "Setting up code signing"
          keychain initialize
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Install CocoaPods
        script: |
          cd ios && pod install
      - name: Set up code signing
        script: |
          xcode-project use-profiles
      - name: Flutter build for iOS simulator
        script: |
          flutter build ios --debug --no-codesign --simulator
          find build/ios/iphonesimulator -name "*.app" -exec zip -r "ios_simulator_app.zip" {} \;
    artifacts:
      - build/ios/iphonesimulator/*.app
      - ios_simulator_app.zip
    publishing:
      email:
        recipients:
          - user@example.com
      scripts:
        - echo "Build completed" 